// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKyIEJ-ipFelohkvGzqk43uV0r7bCQ5zY',
    appId: '1:229173053553:web:10dfeb2ecffac3a305b3d0',
    messagingSenderId: '229173053553',
    projectId: 'myemojiflutter',
    authDomain: 'myemojiflutter.firebaseapp.com',
    storageBucket: 'myemojiflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG5AVo9J226f6tFKrjTDUxx72PhHfFCgQ',
    appId: '1:229173053553:android:bda800e8f76d480105b3d0',
    messagingSenderId: '229173053553',
    projectId: 'myemojiflutter',
    storageBucket: 'myemojiflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIE_b1uV8o2aUxTLhFdRFA6u83Yfzx9lE',
    appId: '1:229173053553:ios:40c804d299a999e205b3d0',
    messagingSenderId: '229173053553',
    projectId: 'myemojiflutter',
    storageBucket: 'myemojiflutter.appspot.com',
    iosClientId: '229173053553-ej1r7jn8jf56dipeetogkafcbtdgi51d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myemoji',
  );
}
